language: csharp
mono: none
dotnet: 2.1
jobs:
  include:
    - stage: "prepare"
      name: "Prepare"
      script:
        - dotnet tool install --global dotnet-sonarscanner
        - dotnet restore
    - stage: "test"
      name: "Test"
      script: 
        - dotnet test SimplePrefixTests/SimplePrefixTests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - stage: "analyze"
      name: "Analyze"
      script:
        - dotnet sonarscanner begin /k:"pichlermarc_SimplePrefix" /o:"pichlermarc-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.opencover.reportsPaths="SimplePrefixTests/coverage.opencover.xml"
        - dotnet build
        - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"